/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/index.html", "./src/**/*.{ts,tsx,js,jsx,html}"],
  theme: {
    extend: {
      colors: {
        white: "rgb(var(--color-white) / <alpha-value>)",
        background: {
          DEFAULT: "rgb(var(--color-background) / <alpha-value>)",
          deep: "rgb(var(--color-background-deep) / <alpha-value>)",
        },
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--color-primary-container) / <alpha-value>)",
        "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary) / <alpha-value>)",
        tertiary: "rgb(var(--color-tertiary) / <alpha-value>)",
        text: {
          primary: "rgb(var(--color-text-primary) / <alpha-value>)",
          secondary: "rgb(var(--color-text-secondary) / <alpha-value>)",
        },
        surface: {
          DEFAULT: "rgb(var(--color-surface) / <alpha-value>)",
          container: {
            low: "rgb(var(--color-surface-container-low) / <alpha-value>)",
            lowest: "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
            high: "rgb(var(--color-surface-container-high) / <alpha-value>)",
            highest: "rgb(var(--color-surface-container-highest) / <alpha-value>)",
          },
          variant: "rgb(var(--color-surface-variant) / <alpha-value>)",
        },
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
        "primary-fixed": "rgb(var(--color-primary-fixed) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--color-tertiary-fixed) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)",
        "error-container": "rgb(var(--color-error-container) / <alpha-value>)",
        "on-error-container": "rgb(var(--color-on-error-container) / <alpha-value>)",
        error: "rgb(var(--color-tertiary) / <alpha-value>)",
        slate: {
          50: "rgb(var(--color-slate-50) / <alpha-value>)",
          100: "rgb(var(--color-slate-100) / <alpha-value>)",
          200: "rgb(var(--color-slate-200) / <alpha-value>)",
          300: "rgb(var(--color-slate-300) / <alpha-value>)",
          400: "rgb(var(--color-slate-400) / <alpha-value>)",
          500: "rgb(var(--color-slate-500) / <alpha-value>)",
          600: "rgb(var(--color-slate-600) / <alpha-value>)",
          700: "rgb(var(--color-slate-700) / <alpha-value>)",
          800: "rgb(var(--color-slate-800) / <alpha-value>)",
          900: "rgb(var(--color-slate-900) / <alpha-value>)",
        },
        emerald: {
          50: "#EEF8EF",
          100: "#D6EFD9",
          200: "#BEE2C4",
          300: "#9BD0A3",
          400: "#76B882",
          500: "#57A165",
          600: "#3E8750",
          700: "#2F6F3F",
          800: "#255936",
          900: "#1D4328",
        },
        amber: {
          50: "#FFF7E5",
          100: "#F9E7BC",
          200: "#F2D692",
          300: "#E7C264",
          400: "#D7AB3F",
          500: "#C18F2B",
          600: "#9D7323",
          700: "#7A5A1B",
          800: "#5F4515",
          900: "#483310",
        },
        sky: {
          50: "#EEF8F7",
          100: "#D8EBE7",
          200: "#B8DAD5",
          300: "#95C5BD",
          400: "#72ADA4",
          500: "#588F88",
          600: "#476F6A",
          700: "#395853",
          800: "#2D4642",
          900: "#223533",
        },
        violet: {
          50: "#F5EFF8",
          100: "#E8DDEE",
          200: "#D3C4DA",
          300: "#BC9FC5",
          400: "#A57BAE",
          500: "#8B5F92",
          600: "#724D76",
          700: "#5A3D5D",
          800: "#462F49",
          900: "#352537",
        },
        rose: {
          50: "#FDF1F2",
          100: "#F7DDE1",
          200: "#EFC0C7",
          300: "#E797A1",
          400: "#D9717D",
          500: "#BE5664",
          600: "#9D4250",
          700: "#80343F",
          800: "#652831",
          900: "#4D1E25",
        },
        brand: {
          primary: "rgb(var(--color-brand-primary) / <alpha-value>)",
          secondary: "rgb(var(--color-brand-secondary) / <alpha-value>)",
          tertiary: "rgb(var(--color-brand-tertiary) / <alpha-value>)",
          neutral: "rgb(var(--color-brand-neutral) / <alpha-value>)",
        },
      },
      fontFamily: {
        sans: ["var(--serene-font-family)", "Inter", "sans-serif"],
        display: ["Manrope", "sans-serif"],
        brand: ["Sora", "sans-serif"],
      },
      borderRadius: {
        sm: "0.5rem",
        md: "0.75rem",
      },
      boxShadow: {
        ambient: "var(--serene-shadow-ambient)",
        float: "var(--serene-shadow-float)",
        "cta-soft": "var(--serene-shadow-cta-soft)",
      },
      backdropBlur: {
        serene: "12px",
      },
    },
  },
  plugins: [],
};
