/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/index.html", "./src/**/*.{ts,tsx,js,jsx,html}"],
  theme: {
    extend: {
      colors: {
        white: "rgb(var(--color-white) / <alpha-value>)",
        background: {
          DEFAULT: "rgb(var(--color-background) / <alpha-value>)",
          deep: "rgb(var(--color-background-deep) / <alpha-value>)",
        },
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--color-primary-container) / <alpha-value>)",
        "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary) / <alpha-value>)",
        tertiary: "rgb(var(--color-tertiary) / <alpha-value>)",
        text: {
          primary: "rgb(var(--color-text-primary) / <alpha-value>)",
          secondary: "rgb(var(--color-text-secondary) / <alpha-value>)",
        },
        surface: {
          DEFAULT: "rgb(var(--color-surface) / <alpha-value>)",
          container: {
            low: "rgb(var(--color-surface-container-low) / <alpha-value>)",
            lowest: "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
            high: "rgb(var(--color-surface-container-high) / <alpha-value>)",
            highest: "rgb(var(--color-surface-container-highest) / <alpha-value>)",
          },
          variant: "rgb(var(--color-surface-variant) / <alpha-value>)",
        },
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
        "primary-fixed": "rgb(var(--color-primary-fixed) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--color-tertiary-fixed) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)",
        "error-container": "rgb(var(--color-error-container) / <alpha-value>)",
        "on-error-container": "rgb(var(--color-on-error-container) / <alpha-value>)",
        error: "rgb(var(--color-tertiary) / <alpha-value>)",
        slate: {
          50: "rgb(var(--color-slate-50) / <alpha-value>)",
          100: "rgb(var(--color-slate-100) / <alpha-value>)",
          200: "rgb(var(--color-slate-200) / <alpha-value>)",
          300: "rgb(var(--color-slate-300) / <alpha-value>)",
          400: "rgb(var(--color-slate-400) / <alpha-value>)",
          500: "rgb(var(--color-slate-500) / <alpha-value>)",
          600: "rgb(var(--color-slate-600) / <alpha-value>)",
          700: "rgb(var(--color-slate-700) / <alpha-value>)",
          800: "rgb(var(--color-slate-800) / <alpha-value>)",
          900: "rgb(var(--color-slate-900) / <alpha-value>)",
        },
        emerald: {
          50: "rgb(var(--color-emerald-50) / <alpha-value>)",
          100: "rgb(var(--color-emerald-100) / <alpha-value>)",
          200: "rgb(var(--color-emerald-200) / <alpha-value>)",
          300: "rgb(var(--color-emerald-300) / <alpha-value>)",
          400: "rgb(var(--color-emerald-400) / <alpha-value>)",
          500: "rgb(var(--color-emerald-500) / <alpha-value>)",
          600: "rgb(var(--color-emerald-600) / <alpha-value>)",
          700: "rgb(var(--color-emerald-700) / <alpha-value>)",
          800: "rgb(var(--color-emerald-800) / <alpha-value>)",
          900: "rgb(var(--color-emerald-900) / <alpha-value>)",
        },
        amber: {
          50: "rgb(var(--color-amber-50) / <alpha-value>)",
          100: "rgb(var(--color-amber-100) / <alpha-value>)",
          200: "rgb(var(--color-amber-200) / <alpha-value>)",
          300: "rgb(var(--color-amber-300) / <alpha-value>)",
          400: "rgb(var(--color-amber-400) / <alpha-value>)",
          500: "rgb(var(--color-amber-500) / <alpha-value>)",
          600: "rgb(var(--color-amber-600) / <alpha-value>)",
          700: "rgb(var(--color-amber-700) / <alpha-value>)",
          800: "rgb(var(--color-amber-800) / <alpha-value>)",
          900: "rgb(var(--color-amber-900) / <alpha-value>)",
        },
        sky: {
          50: "rgb(var(--color-sky-50) / <alpha-value>)",
          100: "rgb(var(--color-sky-100) / <alpha-value>)",
          200: "rgb(var(--color-sky-200) / <alpha-value>)",
          300: "rgb(var(--color-sky-300) / <alpha-value>)",
          400: "rgb(var(--color-sky-400) / <alpha-value>)",
          500: "rgb(var(--color-sky-500) / <alpha-value>)",
          600: "rgb(var(--color-sky-600) / <alpha-value>)",
          700: "rgb(var(--color-sky-700) / <alpha-value>)",
          800: "rgb(var(--color-sky-800) / <alpha-value>)",
          900: "rgb(var(--color-sky-900) / <alpha-value>)",
        },
        violet: {
          50: "rgb(var(--color-violet-50) / <alpha-value>)",
          100: "rgb(var(--color-violet-100) / <alpha-value>)",
          200: "rgb(var(--color-violet-200) / <alpha-value>)",
          300: "rgb(var(--color-violet-300) / <alpha-value>)",
          400: "rgb(var(--color-violet-400) / <alpha-value>)",
          500: "rgb(var(--color-violet-500) / <alpha-value>)",
          600: "rgb(var(--color-violet-600) / <alpha-value>)",
          700: "rgb(var(--color-violet-700) / <alpha-value>)",
          800: "rgb(var(--color-violet-800) / <alpha-value>)",
          900: "rgb(var(--color-violet-900) / <alpha-value>)",
        },
        rose: {
          50: "rgb(var(--color-rose-50) / <alpha-value>)",
          100: "rgb(var(--color-rose-100) / <alpha-value>)",
          200: "rgb(var(--color-rose-200) / <alpha-value>)",
          300: "rgb(var(--color-rose-300) / <alpha-value>)",
          400: "rgb(var(--color-rose-400) / <alpha-value>)",
          500: "rgb(var(--color-rose-500) / <alpha-value>)",
          600: "rgb(var(--color-rose-600) / <alpha-value>)",
          700: "rgb(var(--color-rose-700) / <alpha-value>)",
          800: "rgb(var(--color-rose-800) / <alpha-value>)",
          900: "rgb(var(--color-rose-900) / <alpha-value>)",
        },
        brand: {
          primary: "rgb(var(--color-brand-primary) / <alpha-value>)",
          secondary: "rgb(var(--color-brand-secondary) / <alpha-value>)",
          tertiary: "rgb(var(--color-brand-tertiary) / <alpha-value>)",
          neutral: "rgb(var(--color-brand-neutral) / <alpha-value>)",
        },
      },
      fontFamily: {
        sans: ["var(--serene-font-family)", "Inter", "sans-serif"],
        display: ["Manrope", "sans-serif"],
        brand: ["Sora", "sans-serif"],
      },
      borderRadius: {
        sm: "0.5rem",
        md: "0.75rem",
      },
      boxShadow: {
        ambient: "var(--serene-shadow-ambient)",
        float: "var(--serene-shadow-float)",
        "cta-soft": "var(--serene-shadow-cta-soft)",
      },
      backdropBlur: {
        serene: "12px",
      },
    },
  },
  plugins: [],
};
