import type { DummyGroupSeed, GroupData } from "./app-domain-types";

type BaseGroupFixtureDependencies = {
  musyrifAvatar: string;
  getLocalIsoDateWithOffset: (days: number) => string;
  formatScheduleDate: (isoDate: string) => { date: string; year: string };
};

export function createBaseGroupsFixture({
  musyrifAvatar,
  getLocalIsoDateWithOffset,
  formatScheduleDate,
}: BaseGroupFixtureDependencies): GroupData[] {
const checklistTwoBusTomorrowIso = getLocalIsoDateWithOffset(1);
const checklistTwoBusPastIso = getLocalIsoDateWithOffset(-4);
const checklistTwoBusTomorrowDisplay = formatScheduleDate(checklistTwoBusTomorrowIso);
const checklistTwoBusPastDisplay = formatScheduleDate(checklistTwoBusPastIso);

return [
  {
    code: "901794508",
    name: "Majestic Umrah Group",
    status: "Active",
    tone: "active",
    pax: 70,
    totalBuses: 2,
    packageName: "Standard Gold",
    durationDays: 14,
    timeline: [
      { date: "2 Apr", title: "Jeddah Arrival & Transfer" },
      {
        date: "3 Apr",
        title: "Makkah City Ziyarah",
        isCurrent: true,
        nextActivity: "Bus Boarding (08:30)",
      },
    ],
    nextActivity: {
      title: "Makkah City Ziyarah",
      date: "3 Apr",
      time: "08:30",
      icon: "tour",
    },
    itinerary: [
      {
        date: "2 Apr",
        year: "2026",
        category: "Arrival",
        categoryKey: "arrival",
        title: "Jeddah Arrival and Airport Transfer",
        meta: "04:20 | SV-827 | Hajj Terminal",
        icon: "flight_land",
        flightNumber: "SV-827",
        isoDate: "2026-04-02",
        time: "04:20",
        from: "JED Airport",
        to: "Makkah",
      },
      {
        date: "2 Apr",
        year: "2026",
        category: "Arrival",
        categoryKey: "arrival",
        title: "Hotel Check-in Makkah",
        meta: "11:00 | Swissotel Al Maqam",
        icon: "flight_land",
        isoDate: "2026-04-02",
        time: "11:00",
        from: "Makkah Arrival Point",
        to: "Swissotel Al Maqam",
      },
      {
        date: "3 Apr",
        year: "2026",
        category: "City Tour",
        categoryKey: "city-tour",
        title: "Makkah City Ziyarah",
        meta: "08:30 | Bus 02 | Gate A",
        icon: "tour",
        highlighted: true,
        isoDate: "2026-04-03",
        time: "08:30",
        from: "Makkah Hotel",
        to: "Jabal Rahmah",
        cityTourCity: "Makkah",
        requiresBus: true,
      },
    ],
    notes: [
      "Airport transfer driver needs final reconfirmation before arrival.",
      "Hotel team requested the final rooming list for extra bed allocation.",
    ],
    musyrif: {
      name: "Ust. Ahmad Hidayat",
      phone: "+62 812-3456-7890",
      avatar: musyrifAvatar,
    },
  },
  {
    code: "901794509",
    name: "Honeymoon Special",
    status: "Active",
    tone: "active",
    pax: 12,
    totalBuses: 2,
    packageName: "VIP Deluxe",
    durationDays: 12,
    timeline: [
      { date: "3 Apr", title: "Departure from Jakarta" },
      {
        date: "4 Apr",
        title: "Check-in Madinah Hotel",
        isCurrent: true,
        nextActivity: "Room Distribution",
      },
    ],
    nextActivity: {
      title: "Check-in Madinah Hotel",
      date: "4 Apr",
      time: "14:00",
      icon: "hotel",
    },
    itinerary: [
      {
        date: "3 Apr",
        year: "2026",
        category: "Departure",
        categoryKey: "departure",
        title: "Departure CGK to Madinah",
        meta: "09:30 | SV-819 | Terminal 3",
        icon: "flight_takeoff",
        flightNumber: "SV-819",
        isoDate: "2026-04-03",
        time: "09:30",
        hotelPickupRequestTime: "06:30",
        from: "Jakarta",
        to: "CGK Airport",
      },
      {
        date: "4 Apr",
        year: "2026",
        category: "Arrival",
        categoryKey: "arrival",
        title: "Madinah Hotel Arrival",
        meta: "14:00 | Pullman Zamzam Madinah",
        icon: "flight_land",
        highlighted: true,
        isoDate: "2026-04-04",
        time: "14:00",
        from: "MED Airport",
        to: "Madinah",
      },
      {
        date: "4 Apr",
        year: "2026",
        category: "Transfer",
        categoryKey: "transfer",
        title: "Transfer Haramain High Speed Railway",
        meta: "13:15 | HHR Transfer | Madinah ke Makkah",
        icon: "airport_shuttle",
        isoDate: "2026-04-04",
        time: "13:15",
        from: "Madinah",
        to: "Makkah",
        requiresBus: true,
        transferByTrain: true,
        trainDepartureTime: "13:15",
        destinationPickupTime: "15:35",
      },
      {
        date: "4 Apr",
        year: "2026",
        category: "City Tour",
        categoryKey: "city-tour",
        title: "Rawdah Entry Coordination",
        meta: "07:00 | Lobby Assembly Point",
        icon: "tour",
        isoDate: "2026-04-04",
        time: "07:00",
        from: "Madinah Hotel",
        to: "Rawdah Gate",
        cityTourCity: "Madinah",
      },
    ],
    notes: [
      "Welcome amenity for the VIP rooms should be placed before 13:00.",
      "Need a final seat map for the airport buggy service booking.",
    ],
    musyrif: {
      name: "Ust. Faris Maulana",
      phone: "+62 811-9900-7722",
      avatar: musyrifAvatar,
    },
  },
  {
    code: "901794510",
    name: "Family Group C",
    status: "In Active",
    tone: "inactive",
    pax: 32,
    packageName: "Economic",
    durationDays: 13,
    timeline: [
      { date: "4 Apr", title: "Final Departure Briefing" },
      {
        date: "5 Apr",
        title: "Airport Assembly",
        isCurrent: true,
        nextActivity: "Document Verification",
      },
    ],
    nextActivity: {
      title: "Airport Assembly",
      date: "5 Apr",
      time: "06:30",
      icon: "flight_takeoff",
    },
    itinerary: [
      {
        date: "4 Apr",
        year: "2026",
        category: "Departure",
        categoryKey: "departure",
        title: "Final Departure Briefing",
        meta: "19:30 | Office Hall | Session C",
        icon: "flight_takeoff",
        isoDate: "2026-04-04",
        time: "19:30",
        hotelPickupRequestTime: "17:00",
        from: "Jakarta",
        to: "CGK Airport",
      },
      {
        date: "5 Apr",
        year: "2026",
        category: "Departure",
        categoryKey: "departure",
        title: "Airport Assembly",
        meta: "06:30 | Terminal 3 | Gate C",
        icon: "flight_takeoff",
        highlighted: true,
        isoDate: "2026-04-05",
        time: "06:30",
        hotelPickupRequestTime: "04:30",
        from: "Jakarta",
        to: "CGK Airport",
      },
      {
        date: "5 Apr",
        year: "2026",
        category: "Departure",
        categoryKey: "departure",
        title: "Departure to Jeddah",
        meta: "09:45 | SV-835 | Terminal 3",
        icon: "flight_takeoff",
        flightNumber: "SV-835",
        isoDate: "2026-04-05",
        time: "09:45",
        hotelPickupRequestTime: "07:00",
        from: "Jakarta",
        to: "CGK Airport",
      },
    ],
    notes: [
      "Three passports are still pending courier confirmation.",
      "Family room allocation needs a final review for connecting rooms.",
    ],
    musyrif: {
      name: "Ust. Yusuf Akbar",
      phone: "+62 813-7008-2200",
      avatar: musyrifAvatar,
    },
  },
  {
    code: "901794526",
    name: "Checklist 2 Bus Trial",
    status: "Active",
    tone: "active",
    pax: 70,
    totalBuses: 2,
    packageName: "Standard Gold",
    durationDays: 10,
    timeline: [
      { date: checklistTwoBusPastDisplay.date, title: "Jeddah Arrival & Transfer" },
      {
        date: checklistTwoBusTomorrowDisplay.date,
        title: "Madinah City Tour",
        isCurrent: true,
        nextActivity: "Driver Briefing (08:00)",
      },
    ],
    nextActivity: {
      title: "Madinah City Tour",
      date: checklistTwoBusTomorrowDisplay.date,
      time: "08:00",
      icon: "tour",
    },
    itinerary: [
      {
        date: checklistTwoBusPastDisplay.date,
        year: checklistTwoBusPastDisplay.year,
        category: "Arrival",
        categoryKey: "arrival",
        title: "Jeddah Arrival and Transfer",
        meta: "04:30 | SV-902 | Hajj Terminal",
        icon: "flight_land",
        flightNumber: "SV-902",
        isoDate: checklistTwoBusPastIso,
        time: "04:30",
        from: "JED Airport",
        to: "Madinah",
        requiresBus: true,
      },
      {
        date: checklistTwoBusTomorrowDisplay.date,
        year: checklistTwoBusTomorrowDisplay.year,
        category: "City Tour",
        categoryKey: "city-tour",
        title: "Madinah City Tour",
        meta: "08:00 | Bus 01 & 02 | Hotel Lobby",
        icon: "tour",
        highlighted: true,
        isoDate: checklistTwoBusTomorrowIso,
        time: "08:00",
        from: "Madinah Hotel",
        to: "Quba Mosque",
        cityTourCity: "Madinah",
        requiresBus: true,
      },
    ],
    notes: [
      "Demo group for validating two-bus assignment flow in H-1 checklist.",
      "Can be removed after QA verification.",
    ],
    musyrif: {
      name: "Ust. Demo Driver",
      phone: "+62 812-0000-5260",
      avatar: musyrifAvatar,
    },
  },
];
}

export const overviewDummySeeds: DummyGroupSeed[] = [
  {
    code: "901794511",
    name: "An-Nur Jakarta Batch",
    tone: "active",
    pax: 38,
    packageName: "Standard Silver",
    durationDays: 12,
    startDay: 2,
    musyrifName: "Ust. Ridwan Fauzi",
    musyrifPhone: "+62 812-1001-2201",
  },
  {
    code: "901794512",
    name: "Ar-Rahmah Family Group",
    tone: "inactive",
    pax: 29,
    packageName: "Economic",
    durationDays: 13,
    startDay: 2,
    musyrifName: "Ust. Khalid Amir",
    musyrifPhone: "+62 812-1001-2202",
  },
  {
    code: "901794513",
    name: "Nurul Iman Bandung",
    tone: "inactive",
    pax: 41,
    packageName: "Standard Gold",
    durationDays: 14,
    startDay: 3,
    musyrifName: "Ust. Salman Azmi",
    musyrifPhone: "+62 812-1001-2203",
  },
  {
    code: "901794514",
    name: "Madinah Executive Team",
    tone: "active",
    pax: 24,
    packageName: "VIP Deluxe",
    durationDays: 11,
    startDay: 3,
    musyrifName: "Ust. Dany Iskandar",
    musyrifPhone: "+62 812-1001-2204",
  },
  {
    code: "901794515",
    name: "Al-Hikmah Surabaya",
    tone: "inactive",
    pax: 34,
    packageName: "Standard Gold",
    durationDays: 12,
    startDay: 4,
    musyrifName: "Ust. Bima Rasyid",
    musyrifPhone: "+62 812-1001-2205",
  },
  {
    code: "901794516",
    name: "Safa Marwah Couple",
    tone: "active",
    pax: 16,
    packageName: "VIP Deluxe",
    durationDays: 10,
    startDay: 4,
    musyrifName: "Ust. Fahri Mahesa",
    musyrifPhone: "+62 812-1001-2206",
  },
  {
    code: "901794517",
    name: "Darussalam Community",
    tone: "inactive",
    pax: 36,
    packageName: "Standard Silver",
    durationDays: 13,
    startDay: 5,
    musyrifName: "Ust. Yogi Pratama",
    musyrifPhone: "+62 812-1001-2207",
  },
  {
    code: "901794518",
    name: "Al-Barokah Premium",
    tone: "active",
    pax: 27,
    packageName: "Standard Gold",
    durationDays: 12,
    startDay: 6,
    musyrifName: "Ust. Irfan Ramadhan",
    musyrifPhone: "+62 812-1001-2208",
  },
  {
    code: "901794519",
    name: "Ummul Qura Team",
    tone: "inactive",
    pax: 43,
    packageName: "Economic",
    durationDays: 14,
    startDay: 7,
    musyrifName: "Ust. Rafi Hidayat",
    musyrifPhone: "+62 812-1001-2209",
  },
  {
    code: "901794520",
    name: "Zamzam Family Circle",
    tone: "active",
    pax: 31,
    packageName: "Standard Silver",
    durationDays: 12,
    startDay: 8,
    musyrifName: "Ust. Ali Mubarok",
    musyrifPhone: "+62 812-1001-2210",
  },
  {
    code: "901794521",
    name: "Haramain West Java",
    tone: "inactive",
    pax: 33,
    packageName: "Standard Gold",
    durationDays: 13,
    startDay: 9,
    musyrifName: "Ust. Ghani Akbar",
    musyrifPhone: "+62 812-1001-2211",
  },
  {
    code: "901794522",
    name: "Quba Pioneer Group",
    tone: "active",
    pax: 22,
    packageName: "Economic",
    durationDays: 11,
    startDay: 10,
    musyrifName: "Ust. Rizky Maulana",
    musyrifPhone: "+62 812-1001-2212",
  },
  {
    code: "901794523",
    name: "Hijrah Care Medan",
    tone: "inactive",
    pax: 30,
    packageName: "Standard Silver",
    durationDays: 12,
    startDay: 11,
    musyrifName: "Ust. Naufal Rahman",
    musyrifPhone: "+62 812-1001-2213",
  },
  {
    code: "901794524",
    name: "Arafah Women Group",
    tone: "active",
    pax: 18,
    packageName: "VIP Deluxe",
    durationDays: 10,
    startDay: 12,
    musyrifName: "Ust. Harits Akmal",
    musyrifPhone: "+62 812-1001-2214",
  },
  {
    code: "901794525",
    name: "Makkah Service Unit",
    tone: "inactive",
    pax: 40,
    packageName: "Standard Gold",
    durationDays: 13,
    startDay: 13,
    musyrifName: "Ust. Fikri Ardian",
    musyrifPhone: "+62 812-1001-2215",
  },
];

export const groups: GroupData[] = [];
