import {
  buildVisaAgreementNumber,
  buildVisaTrackingRowsFromGroups,
  formatVisaDateWithYear,
  formatVisaLongDate,
  formatVisaShortDate,
  getGroupAgreementHotelsByCity,
  hasMissingHotelAllocation,
  isIsoDateValue,
  isVisaRowActionRequired,
  resolveValidRaudhahAppointments,
  resolveVisaAgreementDateRange,
  resolveVisaAgreementNumber,
  resolveVisaProvider,
  shiftIsoDate,
} from "./visa-domain.js";
import {
  formatLocalIsoDate,
  getItineraryIsoDate,
  getLocalIsoDateWithOffset,
  parseDisplayDateToIso,
  parseTimeForInput,
} from "./app-domain-core.js";
import {
  CHECKLIST_PAGE_SIZE,
  MAX_PAX_PER_BUS,
  OVERVIEW_PAGE_SIZE,
  VISA_PAGE_SIZE,
  buildChecklistActivityLabel,
  buildChecklistItemsFromGroups,
  buildItineraryItemFromEditForm,
  buildTransferTrainSummary,
  createEditScheduleForm,
  createEmptyChecklistDriverProfile,
  createEmptyChecklistDraft,
  createInitialInputItineraryForm,
  createInitialNoteForm,
  createInitialScheduleForm,
  createNewGroupAgreementForm,
  createNewGroupRaudhahForm,
  createNoteItems,
  createScheduleMeta,
  detectCityFromText,
  expandInputTransferTrainItems,
  expandTransferTrainItineraryItems,
  formatChecklistCopyDate,
  formatRouteSummary,
  formatScheduleDate,
  formatScheduleTime,
  getChecklistDayLabel,
  getChecklistRangeDates,
  getMinimumBusCountForPax,
  getRouteFieldConfigByCategory,
  getSaudiCityOptions,
  getScheduleTypeOption,
  getStatusByTone,
  getTransferTrainSegmentCategory,
  groups,
  hasIncompleteTransferTrainFields,
  includesKnownKeyword,
  inferCategoryKey,
  inferCityTourCity,
  isCityTourActivityType,
  isDepartureActivityType,
  isFlightActivityType,
  isFridayDate,
  isTransferActivityType,
  nonSaudiLocationKeywords,
  normalizeAgreementCityKey,
  normalizeGroupStatus,
  normalizeSaudiCityValue,
  registerSaudiCityOptions,
  resolveGroupToneByItinerary,
  resolveTotalBusCount,
  saudiCityOptions,
  saudiLocationKeywords,
  scheduleTypeOptions,
  scrollToTop,
  shouldShowFridayCityTourWarning,
  sortInputItineraryItems,
} from "../features/groups/domain.js";
import type {
  GroupData,
  NavItem,
  StatusTone,
} from "./app-domain-types.js";

export type {
  AgreementApprovalStatus,
  BusStatus,
  ChecklistAssignmentStatus,
  ChecklistDriverAssignment,
  ChecklistDriverDraft,
  ChecklistDriverProfile,
  ChecklistItem,
  EditScheduleFormState,
  GroupAgreementHotel,
  GroupChecklistAssignment,
  GroupData,
  GroupRaudhahAppointment,
  GroupRaudhahStatus,
  GroupVisaSetup,
  InputItineraryFormState,
  InputItineraryItem,
  ItineraryItem,
  ItineraryPrefill,
  ItineraryPrefillTrip,
  Musyrif,
  MusyrifFormState,
  NavId,
  NavItem,
  NewGroupAgreementFormState,
  NewGroupItineraryDraft,
  NewGroupRaudhahFormState,
  NextActivity,
  NoteFormState,
  NoteItem,
  ScheduleFormState,
  SessionAccessTier,
  StatusTone,
  TimelineItem,
  TransferTrainFields,
  TransferTrainSegment,
  VisaFilterId,
  VisaHotelEditFormState,
  VisaPaymentStatus,
  VisaRaudhahEditFormState,
  VisaRaudhahTone,
  VisaStatus,
  VisaTrackingRow,
} from "./app-domain-types.js";

export {
  CHECKLIST_PAGE_SIZE,
  MAX_PAX_PER_BUS,
  OVERVIEW_PAGE_SIZE,
  VISA_PAGE_SIZE,
  buildChecklistActivityLabel,
  buildChecklistItemsFromGroups,
  buildVisaAgreementNumber,
  buildVisaTrackingRowsFromGroups,
  buildItineraryItemFromEditForm,
  buildTransferTrainSummary,
  createEditScheduleForm,
  createEmptyChecklistDriverProfile,
  createEmptyChecklistDraft,
  createInitialInputItineraryForm,
  createInitialNoteForm,
  createInitialScheduleForm,
  createNewGroupAgreementForm,
  createNewGroupRaudhahForm,
  createNoteItems,
  createScheduleMeta,
  detectCityFromText,
  expandInputTransferTrainItems,
  expandTransferTrainItineraryItems,
  formatChecklistCopyDate,
  formatLocalIsoDate,
  formatRouteSummary,
  formatScheduleDate,
  formatScheduleTime,
  formatVisaDateWithYear,
  formatVisaLongDate,
  formatVisaShortDate,
  getChecklistDayLabel,
  getChecklistRangeDates,
  getItineraryIsoDate,
  getLocalIsoDateWithOffset,
  getMinimumBusCountForPax,
  getRouteFieldConfigByCategory,
  getGroupAgreementHotelsByCity,
  parseDisplayDateToIso,
  parseTimeForInput,
  getSaudiCityOptions,
  getScheduleTypeOption,
  getStatusByTone,
  getTransferTrainSegmentCategory,
  groups,
  hasMissingHotelAllocation,
  hasIncompleteTransferTrainFields,
  includesKnownKeyword,
  inferCategoryKey,
  inferCityTourCity,
  isIsoDateValue,
  isCityTourActivityType,
  isDepartureActivityType,
  isFlightActivityType,
  isFridayDate,
  isTransferActivityType,
  isVisaRowActionRequired,
  nonSaudiLocationKeywords,
  normalizeAgreementCityKey,
  normalizeGroupStatus,
  normalizeSaudiCityValue,
  registerSaudiCityOptions,
  resolveValidRaudhahAppointments,
  resolveGroupToneByItinerary,
  resolveTotalBusCount,
  resolveVisaAgreementDateRange,
  resolveVisaAgreementNumber,
  resolveVisaProvider,
  saudiCityOptions,
  saudiLocationKeywords,
  scheduleTypeOptions,
  scrollToTop,
  shiftIsoDate,
  shouldShowFridayCityTourWarning,
  sortInputItineraryItems,
};

export const operatorAvatar =
  "https://lh3.googleusercontent.com/aida-public/AB6AXuDYxTyP2luvJIjGFQzfh0xRh0AHPBDoS_l-3WNItTegB4jnCMIfkjN_571ulocggZTAS6voqaMm4EoSA-kfN3SxNgXwoxo3NzlaWM8-b3HQoMbNFooz3nsVQqL3smWPEyp8UBTeqYDJEr1qfnNB68B9-4XfLzbyS06bFPL9b8w1TnJJnp2O_s6gH8MLguE3BOtb8uac28oSHRl62ewwxmQRLXyku6cbSP2nh2BszE7hmDB40X8HQtKF-kOCZ_UOJwRQ4i28LoZ6mys";

export const musyrifAvatar =
  "https://lh3.googleusercontent.com/aida-public/AB6AXuDh2QYe9f16M9LsFkFiiV-OWeoRQURwjlEBJp3y0F89mrcICkRZYBeBkUm_v0qJ-0yBwSt9K_oWvo7_ckbWvElV1I9mW0eNQp13OqJr51wrBQWMtG-BTce2SZQmPAB4D-vi6dN4r1WOZwOLU_Is3wpMQtnpUX0Q6ADcQpch-DsiK9LqNdTe66t4O5_thVoBNA5vZTfaC5uZWCis1rIXwkpdy8jYpB95SGSj2_tepJPL9kV9YNSbfHtNGlUneW0vOtsh7v8XP-XTxvk";

export const sidebarItems: NavItem[] = [
  { id: "overview", label: "Overview", icon: "dashboard" },
  { id: "checklist", label: "H-1 Checklist", icon: "fact_check" },
  { id: "visa", label: "Visa Tracking", icon: "fact_check" },
  { id: "invoice", label: "Invoice", icon: "request_quote" },
  { id: "raudhah-reminder", label: "Raudhah Reminder", icon: "notifications_active" },
];

export const sidebarAccountItem: NavItem = {
  id: "profile",
  label: "Profile",
  icon: "account_circle",
};

export const mobileItems: NavItem[] = [
  { id: "overview", label: "Overview", icon: "dashboard" },
  { id: "checklist", label: "Checklist", icon: "fact_check" },
  { id: "visa", label: "Visa", icon: "fact_check" },
  { id: "profile", label: "Profile", icon: "account_circle" },
];

const checklistTwoBusTodayIso = getLocalIsoDateWithOffset(0);
const checklistTwoBusTomorrowIso = getLocalIsoDateWithOffset(1);
const checklistTwoBusPastIso = getLocalIsoDateWithOffset(-4);
const checklistTwoBusTodayDisplay = formatScheduleDate(checklistTwoBusTodayIso);
const checklistTwoBusTomorrowDisplay = formatScheduleDate(checklistTwoBusTomorrowIso);
const checklistTwoBusPastDisplay = formatScheduleDate(checklistTwoBusPastIso);

export const baseGroups: GroupData[] = [
  {
    code: "901794508",
    name: "Majestic Umrah Group",
    status: "Active",
    tone: "active",
    pax: 70,
    totalBuses: 2,
    packageName: "Standard Gold",
    durationDays: 14,
    timeline: [
      { date: "2 Apr", title: "Jeddah Arrival & Transfer" },
      {
        date: "3 Apr",
        title: "Makkah City Ziyarah",
        isCurrent: true,
        nextActivity: "Bus Boarding (08:30)",
      },
    ],
    nextActivity: {
      title: "Makkah City Ziyarah",
      date: "3 Apr",
      time: "08:30",
      icon: "tour",
    },
    itinerary: [
      {
        date: "2 Apr",
        year: "2026",
        category: "Arrival",
        categoryKey: "arrival",
        title: "Jeddah Arrival and Airport Transfer",
        meta: "04:20 | SV-827 | Hajj Terminal",
        icon: "flight_land",
        flightNumber: "SV-827",
        isoDate: "2026-04-02",
        time: "04:20",
        from: "JED Airport",
        to: "Makkah",
      },
      {
        date: "2 Apr",
        year: "2026",
        category: "Arrival",
        categoryKey: "arrival",
        title: "Hotel Check-in Makkah",
        meta: "11:00 | Swissotel Al Maqam",
        icon: "flight_land",
        isoDate: "2026-04-02",
        time: "11:00",
        from: "Makkah Arrival Point",
        to: "Swissotel Al Maqam",
      },
      {
        date: "3 Apr",
        year: "2026",
        category: "City Tour",
        categoryKey: "city-tour",
        title: "Makkah City Ziyarah",
        meta: "08:30 | Bus 02 | Gate A",
        icon: "tour",
        highlighted: true,
        isoDate: "2026-04-03",
        time: "08:30",
        from: "Makkah Hotel",
        to: "Jabal Rahmah",
        cityTourCity: "Makkah",
        requiresBus: true,
      },
    ],
    notes: [
      "Airport transfer driver needs final reconfirmation before arrival.",
      "Hotel team requested the final rooming list for extra bed allocation.",
    ],
    musyrif: {
      name: "Ust. Ahmad Hidayat",
      phone: "+62 812-3456-7890",
      avatar: musyrifAvatar,
    },
  },
  {
    code: "901794509",
    name: "Honeymoon Special",
    status: "Active",
    tone: "active",
    pax: 12,
    totalBuses: 2,
    packageName: "VIP Deluxe",
    durationDays: 12,
    timeline: [
      { date: "3 Apr", title: "Departure from Jakarta" },
      {
        date: "4 Apr",
        title: "Check-in Madinah Hotel",
        isCurrent: true,
        nextActivity: "Room Distribution",
      },
    ],
    nextActivity: {
      title: "Check-in Madinah Hotel",
      date: "4 Apr",
      time: "14:00",
      icon: "hotel",
    },
    itinerary: [
      {
        date: "3 Apr",
        year: "2026",
        category: "Departure",
        categoryKey: "departure",
        title: "Departure CGK to Madinah",
        meta: "09:30 | SV-819 | Terminal 3",
        icon: "flight_takeoff",
        flightNumber: "SV-819",
        isoDate: "2026-04-03",
        time: "09:30",
        hotelPickupRequestTime: "06:30",
        from: "Jakarta",
        to: "CGK Airport",
      },
      {
        date: "4 Apr",
        year: "2026",
        category: "Arrival",
        categoryKey: "arrival",
        title: "Madinah Hotel Arrival",
        meta: "14:00 | Pullman Zamzam Madinah",
        icon: "flight_land",
        highlighted: true,
        isoDate: "2026-04-04",
        time: "14:00",
        from: "MED Airport",
        to: "Madinah",
      },
      {
        date: "4 Apr",
        year: "2026",
        category: "Transfer",
        categoryKey: "transfer",
        title: "Transfer Haramain High Speed Railway",
        meta: "13:15 | HHR Transfer | Madinah ke Makkah",
        icon: "airport_shuttle",
        isoDate: "2026-04-04",
        time: "13:15",
        from: "Madinah",
        to: "Makkah",
        requiresBus: true,
        transferByTrain: true,
        trainDepartureTime: "13:15",
        destinationPickupTime: "15:35",
      },
      {
        date: "4 Apr",
        year: "2026",
        category: "City Tour",
        categoryKey: "city-tour",
        title: "Rawdah Entry Coordination",
        meta: "07:00 | Lobby Assembly Point",
        icon: "tour",
        isoDate: "2026-04-04",
        time: "07:00",
        from: "Madinah Hotel",
        to: "Rawdah Gate",
        cityTourCity: "Madinah",
      },
    ],
    notes: [
      "Welcome amenity for the VIP rooms should be placed before 13:00.",
      "Need a final seat map for the airport buggy service booking.",
    ],
    musyrif: {
      name: "Ust. Faris Maulana",
      phone: "+62 811-9900-7722",
      avatar: musyrifAvatar,
    },
  },
  {
    code: "901794510",
    name: "Family Group C",
    status: "In Active",
    tone: "inactive",
    pax: 32,
    packageName: "Economic",
    durationDays: 13,
    timeline: [
      { date: "4 Apr", title: "Final Departure Briefing" },
      {
        date: "5 Apr",
        title: "Airport Assembly",
        isCurrent: true,
        nextActivity: "Document Verification",
      },
    ],
    nextActivity: {
      title: "Airport Assembly",
      date: "5 Apr",
      time: "06:30",
      icon: "flight_takeoff",
    },
    itinerary: [
      {
        date: "4 Apr",
        year: "2026",
        category: "Departure",
        categoryKey: "departure",
        title: "Final Departure Briefing",
        meta: "19:30 | Office Hall | Session C",
        icon: "flight_takeoff",
        isoDate: "2026-04-04",
        time: "19:30",
        hotelPickupRequestTime: "17:00",
        from: "Jakarta",
        to: "CGK Airport",
      },
      {
        date: "5 Apr",
        year: "2026",
        category: "Departure",
        categoryKey: "departure",
        title: "Airport Assembly",
        meta: "06:30 | Terminal 3 | Gate C",
        icon: "flight_takeoff",
        highlighted: true,
        isoDate: "2026-04-05",
        time: "06:30",
        hotelPickupRequestTime: "04:30",
        from: "Jakarta",
        to: "CGK Airport",
      },
      {
        date: "5 Apr",
        year: "2026",
        category: "Departure",
        categoryKey: "departure",
        title: "Departure to Jeddah",
        meta: "09:45 | SV-835 | Terminal 3",
        icon: "flight_takeoff",
        flightNumber: "SV-835",
        isoDate: "2026-04-05",
        time: "09:45",
        hotelPickupRequestTime: "07:00",
        from: "Jakarta",
        to: "CGK Airport",
      },
    ],
    notes: [
      "Three passports are still pending courier confirmation.",
      "Family room allocation needs a final review for connecting rooms.",
    ],
    musyrif: {
      name: "Ust. Yusuf Akbar",
      phone: "+62 813-7008-2200",
      avatar: musyrifAvatar,
    },
  },
  {
    code: "901794526",
    name: "Checklist 2 Bus Trial",
    status: "Active",
    tone: "active",
    pax: 70,
    totalBuses: 2,
    packageName: "Standard Gold",
    durationDays: 10,
    timeline: [
      { date: checklistTwoBusPastDisplay.date, title: "Jeddah Arrival & Transfer" },
      {
        date: checklistTwoBusTomorrowDisplay.date,
        title: "Madinah City Tour",
        isCurrent: true,
        nextActivity: "Driver Briefing (08:00)",
      },
    ],
    nextActivity: {
      title: "Madinah City Tour",
      date: checklistTwoBusTomorrowDisplay.date,
      time: "08:00",
      icon: "tour",
    },
    itinerary: [
      {
        date: checklistTwoBusPastDisplay.date,
        year: checklistTwoBusPastDisplay.year,
        category: "Arrival",
        categoryKey: "arrival",
        title: "Jeddah Arrival and Transfer",
        meta: "04:30 | SV-902 | Hajj Terminal",
        icon: "flight_land",
        flightNumber: "SV-902",
        isoDate: checklistTwoBusPastIso,
        time: "04:30",
        from: "JED Airport",
        to: "Madinah",
        requiresBus: true,
      },
      {
        date: checklistTwoBusTomorrowDisplay.date,
        year: checklistTwoBusTomorrowDisplay.year,
        category: "City Tour",
        categoryKey: "city-tour",
        title: "Madinah City Tour",
        meta: "08:00 | Bus 01 & 02 | Hotel Lobby",
        icon: "tour",
        highlighted: true,
        isoDate: checklistTwoBusTomorrowIso,
        time: "08:00",
        from: "Madinah Hotel",
        to: "Quba Mosque",
        cityTourCity: "Madinah",
        requiresBus: true,
      },
    ],
    notes: [
      "Demo group for validating two-bus assignment flow in H-1 checklist.",
      "Can be removed after QA verification.",
    ],
    musyrif: {
      name: "Ust. Demo Driver",
      phone: "+62 812-0000-5260",
      avatar: musyrifAvatar,
    },
  },
];

export type DummyGroupSeed = {
  code: string;
  name: string;
  tone: StatusTone;
  pax: number;
  packageName: string;
  durationDays: number;
  startDay: number;
  musyrifName: string;
  musyrifPhone: string;
};

export const overviewDummySeeds: DummyGroupSeed[] = [
  {
    code: "901794511",
    name: "An-Nur Jakarta Batch",
    tone: "active",
    pax: 38,
    packageName: "Standard Silver",
    durationDays: 12,
    startDay: 2,
    musyrifName: "Ust. Ridwan Fauzi",
    musyrifPhone: "+62 812-1001-2201",
  },
  {
    code: "901794512",
    name: "Ar-Rahmah Family Group",
    tone: "inactive",
    pax: 29,
    packageName: "Economic",
    durationDays: 13,
    startDay: 2,
    musyrifName: "Ust. Khalid Amir",
    musyrifPhone: "+62 812-1001-2202",
  },
  {
    code: "901794513",
    name: "Nurul Iman Bandung",
    tone: "inactive",
    pax: 41,
    packageName: "Standard Gold",
    durationDays: 14,
    startDay: 3,
    musyrifName: "Ust. Salman Azmi",
    musyrifPhone: "+62 812-1001-2203",
  },
  {
    code: "901794514",
    name: "Madinah Executive Team",
    tone: "active",
    pax: 24,
    packageName: "VIP Deluxe",
    durationDays: 11,
    startDay: 3,
    musyrifName: "Ust. Dany Iskandar",
    musyrifPhone: "+62 812-1001-2204",
  },
  {
    code: "901794515",
    name: "Al-Hikmah Surabaya",
    tone: "inactive",
    pax: 34,
    packageName: "Standard Gold",
    durationDays: 12,
    startDay: 4,
    musyrifName: "Ust. Bima Rasyid",
    musyrifPhone: "+62 812-1001-2205",
  },
  {
    code: "901794516",
    name: "Safa Marwah Couple",
    tone: "active",
    pax: 16,
    packageName: "VIP Deluxe",
    durationDays: 10,
    startDay: 4,
    musyrifName: "Ust. Fahri Mahesa",
    musyrifPhone: "+62 812-1001-2206",
  },
  {
    code: "901794517",
    name: "Darussalam Community",
    tone: "inactive",
    pax: 36,
    packageName: "Standard Silver",
    durationDays: 13,
    startDay: 5,
    musyrifName: "Ust. Yogi Pratama",
    musyrifPhone: "+62 812-1001-2207",
  },
  {
    code: "901794518",
    name: "Al-Barokah Premium",
    tone: "active",
    pax: 27,
    packageName: "Standard Gold",
    durationDays: 12,
    startDay: 6,
    musyrifName: "Ust. Irfan Ramadhan",
    musyrifPhone: "+62 812-1001-2208",
  },
  {
    code: "901794519",
    name: "Ummul Qura Team",
    tone: "inactive",
    pax: 43,
    packageName: "Economic",
    durationDays: 14,
    startDay: 7,
    musyrifName: "Ust. Rafi Hidayat",
    musyrifPhone: "+62 812-1001-2209",
  },
  {
    code: "901794520",
    name: "Zamzam Family Circle",
    tone: "active",
    pax: 31,
    packageName: "Standard Silver",
    durationDays: 12,
    startDay: 8,
    musyrifName: "Ust. Ali Mubarok",
    musyrifPhone: "+62 812-1001-2210",
  },
  {
    code: "901794521",
    name: "Haramain West Java",
    tone: "inactive",
    pax: 33,
    packageName: "Standard Gold",
    durationDays: 13,
    startDay: 9,
    musyrifName: "Ust. Ghani Akbar",
    musyrifPhone: "+62 812-1001-2211",
  },
  {
    code: "901794522",
    name: "Quba Pioneer Group",
    tone: "active",
    pax: 22,
    packageName: "Economic",
    durationDays: 11,
    startDay: 10,
    musyrifName: "Ust. Rizky Maulana",
    musyrifPhone: "+62 812-1001-2212",
  },
  {
    code: "901794523",
    name: "Hijrah Care Medan",
    tone: "inactive",
    pax: 30,
    packageName: "Standard Silver",
    durationDays: 12,
    startDay: 11,
    musyrifName: "Ust. Naufal Rahman",
    musyrifPhone: "+62 812-1001-2213",
  },
  {
    code: "901794524",
    name: "Arafah Women Group",
    tone: "active",
    pax: 18,
    packageName: "VIP Deluxe",
    durationDays: 10,
    startDay: 12,
    musyrifName: "Ust. Harits Akmal",
    musyrifPhone: "+62 812-1001-2214",
  },
  {
    code: "901794525",
    name: "Makkah Service Unit",
    tone: "inactive",
    pax: 40,
    packageName: "Standard Gold",
    durationDays: 13,
    startDay: 13,
    musyrifName: "Ust. Fikri Ardian",
    musyrifPhone: "+62 812-1001-2215",
  },
];

export function formatAprilIsoDate(day: number): string {
  return `2026-04-${String(Math.min(Math.max(day, 1), 30)).padStart(2, "0")}`;
}

export function formatAprilDisplayDate(day: number): string {
  return `${Math.min(Math.max(day, 1), 30)} Apr`;
}

export function createDummyOverviewGroups(): GroupData[] {
  return overviewDummySeeds.map((seed, index) => {
    const departureDay = seed.startDay;
    const arrivalDay = Math.min(seed.startDay + 1, 30);
    const operationDay = Math.min(seed.startDay + 2, 30);
    const departureTime = `${String(5 + (index % 6)).padStart(2, "0")}:${index % 2 === 0 ? "30" : "45"}`;
    const arrivalTime = `${String(9 + (index % 5)).padStart(2, "0")}:${index % 2 === 0 ? "10" : "25"}`;
    const operationTime = `${String(7 + (index % 6)).padStart(2, "0")}:${index % 2 === 0 ? "00" : "15"}`;
    const flightNumber = `SV-${840 + index}`;
    const isCityTour = index % 2 === 0;
    const operationCategory = isCityTour ? "City Tour" : "Transfer";
    const operationCategoryKey = isCityTour ? "city-tour" : "transfer";
    const operationIcon = isCityTour ? "tour" : "airport_shuttle";
    const operationFrom = isCityTour ? "Makkah Hotel" : "Makkah";
    const operationTo = isCityTour ? "Jabal Rahmah" : "Madinah";
    const operationTitle = isCityTour
      ? "Makkah City Ziyarah"
      : "Transfer from Makkah to Madinah";
    const operationMeta = isCityTour
      ? `${formatScheduleTime(operationTime)} | Bus ${String((index % 9) + 1).padStart(2, "0")} | Gate A`
      : `${formatScheduleTime(operationTime)} | Highway Route 40`;

    return {
      code: seed.code,
      name: seed.name,
      status: getStatusByTone(seed.tone),
      tone: seed.tone,
      pax: seed.pax,
      totalBuses: resolveTotalBusCount(seed.pax),
      packageName: seed.packageName,
      durationDays: seed.durationDays,
      timeline: [
        { date: formatAprilDisplayDate(departureDay), title: "Departure from Jakarta" },
        {
          date: formatAprilDisplayDate(operationDay),
          title: operationTitle,
          isCurrent: true,
          nextActivity: `${operationCategory} (${formatScheduleTime(operationTime)})`,
        },
      ],
      nextActivity: {
        title: operationTitle,
        date: formatAprilDisplayDate(operationDay),
        time: operationTime,
        icon: operationIcon,
      },
      itinerary: [
        {
          date: formatAprilDisplayDate(departureDay),
          year: "2026",
          category: "Departure",
          categoryKey: "departure",
          title: "Depart from Jakarta to CGK Airport",
          meta: `${formatScheduleTime(departureTime)} | ${flightNumber} | Terminal 3`,
          icon: "flight_takeoff",
          flightNumber,
          isoDate: formatAprilIsoDate(departureDay),
          time: departureTime,
          hotelPickupRequestTime: departureTime,
          from: "Jakarta",
          to: "CGK Airport",
        },
        {
          date: formatAprilDisplayDate(arrivalDay),
          year: "2026",
          category: "Arrival",
          categoryKey: "arrival",
          title: "Landing at JED Airport and heading to Makkah",
          meta: `${formatScheduleTime(arrivalTime)} | Hajj Terminal | Group Bus`,
          icon: "flight_land",
          isoDate: formatAprilIsoDate(arrivalDay),
          time: arrivalTime,
          from: "JED Airport",
          to: "Makkah",
        },
        {
          date: formatAprilDisplayDate(operationDay),
          year: "2026",
          category: operationCategory,
          categoryKey: operationCategoryKey,
          title: operationTitle,
          meta: operationMeta,
          icon: operationIcon,
          highlighted: true,
          isoDate: formatAprilIsoDate(operationDay),
          time: operationTime,
          from: operationFrom,
          to: operationTo,
          cityTourCity: isCityTour ? operationFrom : "",
          requiresBus: true,
        },
      ],
      notes: [
        "Driver coordination needs reconfirmation 24 hours before schedule.",
        "Rooming and baggage list already shared with ground handling team.",
      ],
      musyrif: {
        name: seed.musyrifName,
        phone: seed.musyrifPhone,
        avatar: musyrifAvatar,
      },
    };
  });
}

export function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

